- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |

      # Ensure Docker exists
      if ! command -v docker &> /dev/null
      then
        sudo apt update
        sudo apt install -y docker.io
        sudo systemctl enable docker
        sudo systemctl start docker
        sudo usermod -aG docker ubuntu
      fi

      # Pull latest image
      docker pull ${{ secrets.DOCKER_USERNAME }}/muchtodo:latest

      # Remove old container
      docker rm -f app || true

      # Run new container
      docker run -d \
        --restart unless-stopped \
        -p 80:8080 \
        -e MONGO_URI="${{ secrets.MONGO_URI }}" \
        -e DB_NAME="starttech" \
        --name app \
        ${{ secrets.DOCKER_USERNAME }}/muchtodo:latest

      # Wait for startup
      sleep 15

      # Validate container is running
      docker ps

      # Validate application responds
      curl -I http://localhost || exit 1
